default: &default
  adapter: postgresql
  port: 5432
  host: localhost
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  schema_search_path: public
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: boards_development

test:
  <<: *default
  database: boards_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
